version: '3.7'
services:
  jenkins:
    build: ./
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 50000:50000
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    file: ./test-user
  jenkins-pass:
    file: ./test-pass